[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  # Disable Next.js telemetry
  NEXT_TELEMETRY_DISABLED = "1"
  # Ensure proper build mode
  NODE_ENV = "production"
  # Force Next.js to use the correct output
  NEXT_SHARP_PATH = ""
  # Force Netlify to detect changes
  NETLIFY_DEPLOY_TIMESTAMP = "2024-07-12-19-30"

[functions]
  node_bundler = "esbuild"

# API routes redirect
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/___netlify-handler"
  status = 200

# Fallback for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 