[build]
  command = "npm run build:netlify"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_ENV = "production"
  SKIP_ENV_VALIDATION = "true"
  NETLIFY_DEPLOY_TIMESTAMP = "2024-07-12-21-30"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Let the plugin handle redirects automatically 