[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_ENV = "production"
  SKIP_ENV_VALIDATION = "true"
  NETLIFY_DEPLOY_TIMESTAMP = "2024-07-12-22-00"
  # Force Next.js to use the correct output
  NEXT_SHARP_PATH = ""
  # Ensure proper build mode
  NEXT_PUBLIC_VERCEL_URL = ""

# Plugin will be configured through Netlify UI 